
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package tw.com.aptg.ws.api.core.profileservice;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2018-03-22T12:05:10.759+08:00
 * Generated source version: 2.7.18
 * 
 */

@javax.jws.WebService(
                      serviceName = "ProfileService",
                      portName = "ProfileServicePort",
                      targetNamespace = "http://www.aptg.com.tw/ws/api/core/ProfileService",
                      wsdlLocation = "http://10.31.79.7:8000/profile-service/ProfileService?wsdl",
                      endpointInterface = "tw.com.aptg.ws.api.core.profileservice.ProfileService")
                      
public class ProfileServiceImpl implements ProfileService {

    private static final Logger LOG = Logger.getLogger(ProfileServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see tw.com.aptg.ws.api.core.profileservice.ProfileService#memberChangeAccount(java.lang.String  serviceID ,)java.lang.String  servicePWD ,)java.lang.String  oldAccountID ,)java.lang.String  personID ,)java.lang.String  newAccountID )*
     */
    public tw.com.aptg.ws.api.core.profileservice.Response memberChangeAccount(java.lang.String serviceID,java.lang.String servicePWD,java.lang.String oldAccountID,java.lang.String personID,java.lang.String newAccountID) { 
        LOG.info("Executing operation memberChangeAccount");
        System.out.println(serviceID);
        System.out.println(servicePWD);
        System.out.println(oldAccountID);
        System.out.println(personID);
        System.out.println(newAccountID);
        try {
            tw.com.aptg.ws.api.core.profileservice.Response _return = new tw.com.aptg.ws.api.core.profileservice.Response();
            _return.setDescription("Description-2035001746");
            tw.com.aptg.ws.api.core.profileservice.Profile _returnProfile = new tw.com.aptg.ws.api.core.profileservice.Profile();
            tw.com.aptg.ws.api.core.profileservice.Acceptance _returnProfileAcceptEpaper = tw.com.aptg.ws.api.core.profileservice.Acceptance.N;
            _returnProfile.setAcceptEpaper(_returnProfileAcceptEpaper);
            _returnProfile.setAddress("Address2007343001");
            _returnProfile.setBc("Bc1628559870");
            _returnProfile.setBirthday("Birthday979382562");
            _returnProfile.setBscsCOID("BscsCOID-1347172474");
            _returnProfile.setBscsCSCODE("BscsCSCODE708408507");
            _returnProfile.setBscsCSID("BscsCSID-1605488655");
            _returnProfile.setCompanyName("CompanyName-1685263611");
            _returnProfile.setContactPhone("ContactPhone835079335");
            _returnProfile.setContractID("ContractID-1923197755");
            tw.com.aptg.ws.api.core.profileservice.YesNoOption _returnProfileContractStatus = tw.com.aptg.ws.api.core.profileservice.YesNoOption.Y;
            _returnProfile.setContractStatus(_returnProfileContractStatus);
            _returnProfile.setContractStatusCode("ContractStatusCode-1461408527");
            _returnProfile.setCustomerID("CustomerID1187677789");
            _returnProfile.setDisableWeb("DisableWeb1637555217");
            _returnProfile.setEducation("Education1452080054");
            _returnProfile.setEmail("Email-1897737006");
            _returnProfile.setEname("Ename-1118835680");
            tw.com.aptg.ws.api.core.profileservice.Gender _returnProfileGender = tw.com.aptg.ws.api.core.profileservice.Gender.F;
            _returnProfile.setGender(_returnProfileGender);
            tw.com.aptg.ws.api.core.profileservice.YesNoOption _returnProfileIsAdult = tw.com.aptg.ws.api.core.profileservice.YesNoOption.Y;
            _returnProfile.setIsAdult(_returnProfileIsAdult);
            _returnProfile.setJobTitle("JobTitle485945176");
            _returnProfile.setMdn("Mdn-715109878");
            _returnProfile.setMin("Min-401600657");
            _returnProfile.setMobile1("Mobile11133937708");
            _returnProfile.setMobile2("Mobile2510728424");
            _returnProfile.setMobilePhoneType("MobilePhoneType1966096573");
            _returnProfile.setName("Name2103337866");
            _returnProfile.setNickname("Nickname410695467");
            _returnProfile.setOccupation("Occupation270465491");
            _returnProfile.setOtpStatus("OtpStatus528310148");
            _returnProfile.setPersonalID("PersonalID-1393839007");
            _returnProfile.setProductType("ProductType211810183");
            _returnProfile.setPromotionCode("PromotionCode-163589687");
            _returnProfile.setPushMail("PushMail1974549688");
            _returnProfile.setSmscMail("SmscMail551650778");
            _returnProfile.setTelphone1("Telphone1805957076");
            _returnProfile.setTelphone2("Telphone299174031");
            _returnProfile.setTerminateType("TerminateType-1888276380");
            _returnProfile.setUid("Uid-1148323260");
            _returnProfile.setUserType("UserType1937353534");
            _return.setProfile(_returnProfile);
            _return.setResultCode("ResultCode-2141328912");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see tw.com.aptg.ws.api.core.profileservice.ProfileService#memberResetPassword(java.lang.String  serviceID ,)java.lang.String  servicePWD ,)java.lang.String  memberID ,)java.lang.String  personID )*
     */
    public tw.com.aptg.ws.api.core.profileservice.Response memberResetPassword(java.lang.String serviceID,java.lang.String servicePWD,java.lang.String memberID,java.lang.String personID) { 
        LOG.info("Executing operation memberResetPassword");
        System.out.println(serviceID);
        System.out.println(servicePWD);
        System.out.println(memberID);
        System.out.println(personID);
        try {
            tw.com.aptg.ws.api.core.profileservice.Response _return = new tw.com.aptg.ws.api.core.profileservice.Response();
            _return.setDescription("Description801674539");
            tw.com.aptg.ws.api.core.profileservice.Profile _returnProfile = new tw.com.aptg.ws.api.core.profileservice.Profile();
            tw.com.aptg.ws.api.core.profileservice.Acceptance _returnProfileAcceptEpaper = tw.com.aptg.ws.api.core.profileservice.Acceptance.N;
            _returnProfile.setAcceptEpaper(_returnProfileAcceptEpaper);
            _returnProfile.setAddress("Address1521561366");
            _returnProfile.setBc("Bc-781079824");
            _returnProfile.setBirthday("Birthday1736291177");
            _returnProfile.setBscsCOID("BscsCOID506675407");
            _returnProfile.setBscsCSCODE("BscsCSCODE808140941");
            _returnProfile.setBscsCSID("BscsCSID2066196039");
            _returnProfile.setCompanyName("CompanyName1938799257");
            _returnProfile.setContactPhone("ContactPhone844380023");
            _returnProfile.setContractID("ContractID936419518");
            tw.com.aptg.ws.api.core.profileservice.YesNoOption _returnProfileContractStatus = tw.com.aptg.ws.api.core.profileservice.YesNoOption.Y;
            _returnProfile.setContractStatus(_returnProfileContractStatus);
            _returnProfile.setContractStatusCode("ContractStatusCode787639542");
            _returnProfile.setCustomerID("CustomerID191532679");
            _returnProfile.setDisableWeb("DisableWeb-1086334735");
            _returnProfile.setEducation("Education-1394343759");
            _returnProfile.setEmail("Email-1215143580");
            _returnProfile.setEname("Ename1168412018");
            tw.com.aptg.ws.api.core.profileservice.Gender _returnProfileGender = tw.com.aptg.ws.api.core.profileservice.Gender.F;
            _returnProfile.setGender(_returnProfileGender);
            tw.com.aptg.ws.api.core.profileservice.YesNoOption _returnProfileIsAdult = tw.com.aptg.ws.api.core.profileservice.YesNoOption.Y;
            _returnProfile.setIsAdult(_returnProfileIsAdult);
            _returnProfile.setJobTitle("JobTitle-1994457201");
            _returnProfile.setMdn("Mdn-1901324471");
            _returnProfile.setMin("Min1689541294");
            _returnProfile.setMobile1("Mobile11522717313");
            _returnProfile.setMobile2("Mobile21261804116");
            _returnProfile.setMobilePhoneType("MobilePhoneType870760269");
            _returnProfile.setName("Name-280069239");
            _returnProfile.setNickname("Nickname-251434922");
            _returnProfile.setOccupation("Occupation-2043065248");
            _returnProfile.setOtpStatus("OtpStatus-1312156988");
            _returnProfile.setPersonalID("PersonalID-273038004");
            _returnProfile.setProductType("ProductType545640193");
            _returnProfile.setPromotionCode("PromotionCode-390497514");
            _returnProfile.setPushMail("PushMail-1135989744");
            _returnProfile.setSmscMail("SmscMail1518482650");
            _returnProfile.setTelphone1("Telphone1864557236");
            _returnProfile.setTelphone2("Telphone21761813430");
            _returnProfile.setTerminateType("TerminateType1781916412");
            _returnProfile.setUid("Uid1606260246");
            _returnProfile.setUserType("UserType1700679149");
            _return.setProfile(_returnProfile);
            _return.setResultCode("ResultCode1771525818");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see tw.com.aptg.ws.api.core.profileservice.ProfileService#setContractEMail(java.lang.String  serviceID ,)java.lang.String  servicePWD ,)java.lang.String  userID ,)java.lang.String  contractID ,)java.lang.String  mdn ,)java.lang.String  min ,)java.lang.String  email )*
     */
    public tw.com.aptg.ws.api.core.profileservice.Response setContractEMail(java.lang.String serviceID,java.lang.String servicePWD,java.lang.String userID,java.lang.String contractID,java.lang.String mdn,java.lang.String min,java.lang.String email) { 
        LOG.info("Executing operation setContractEMail");
        System.out.println(serviceID);
        System.out.println(servicePWD);
        System.out.println(userID);
        System.out.println(contractID);
        System.out.println(mdn);
        System.out.println(min);
        System.out.println(email);
        try {
            tw.com.aptg.ws.api.core.profileservice.Response _return = new tw.com.aptg.ws.api.core.profileservice.Response();
            _return.setDescription("Description-1498075559");
            tw.com.aptg.ws.api.core.profileservice.Profile _returnProfile = new tw.com.aptg.ws.api.core.profileservice.Profile();
            tw.com.aptg.ws.api.core.profileservice.Acceptance _returnProfileAcceptEpaper = tw.com.aptg.ws.api.core.profileservice.Acceptance.N;
            _returnProfile.setAcceptEpaper(_returnProfileAcceptEpaper);
            _returnProfile.setAddress("Address110639919");
            _returnProfile.setBc("Bc-838630013");
            _returnProfile.setBirthday("Birthday844335817");
            _returnProfile.setBscsCOID("BscsCOID1735015578");
            _returnProfile.setBscsCSCODE("BscsCSCODE-238426635");
            _returnProfile.setBscsCSID("BscsCSID910067253");
            _returnProfile.setCompanyName("CompanyName-917931302");
            _returnProfile.setContactPhone("ContactPhone-757401051");
            _returnProfile.setContractID("ContractID909237475");
            tw.com.aptg.ws.api.core.profileservice.YesNoOption _returnProfileContractStatus = tw.com.aptg.ws.api.core.profileservice.YesNoOption.Y;
            _returnProfile.setContractStatus(_returnProfileContractStatus);
            _returnProfile.setContractStatusCode("ContractStatusCode1146451030");
            _returnProfile.setCustomerID("CustomerID-292446421");
            _returnProfile.setDisableWeb("DisableWeb427284286");
            _returnProfile.setEducation("Education1752285405");
            _returnProfile.setEmail("Email497405656");
            _returnProfile.setEname("Ename-188502043");
            tw.com.aptg.ws.api.core.profileservice.Gender _returnProfileGender = tw.com.aptg.ws.api.core.profileservice.Gender.M;
            _returnProfile.setGender(_returnProfileGender);
            tw.com.aptg.ws.api.core.profileservice.YesNoOption _returnProfileIsAdult = tw.com.aptg.ws.api.core.profileservice.YesNoOption.Y;
            _returnProfile.setIsAdult(_returnProfileIsAdult);
            _returnProfile.setJobTitle("JobTitle-514160734");
            _returnProfile.setMdn("Mdn540258146");
            _returnProfile.setMin("Min-2088679966");
            _returnProfile.setMobile1("Mobile12110194928");
            _returnProfile.setMobile2("Mobile237678766");
            _returnProfile.setMobilePhoneType("MobilePhoneType-147863273");
            _returnProfile.setName("Name721597539");
            _returnProfile.setNickname("Nickname-348799415");
            _returnProfile.setOccupation("Occupation-322399998");
            _returnProfile.setOtpStatus("OtpStatus1175654041");
            _returnProfile.setPersonalID("PersonalID-629259157");
            _returnProfile.setProductType("ProductType-435417075");
            _returnProfile.setPromotionCode("PromotionCode896136264");
            _returnProfile.setPushMail("PushMail1903578536");
            _returnProfile.setSmscMail("SmscMail359456232");
            _returnProfile.setTelphone1("Telphone1-1619962950");
            _returnProfile.setTelphone2("Telphone21763506077");
            _returnProfile.setTerminateType("TerminateType-1349926289");
            _returnProfile.setUid("Uid-1790857636");
            _returnProfile.setUserType("UserType-1349425224");
            _return.setProfile(_returnProfile);
            _return.setResultCode("ResultCode1894903208");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see tw.com.aptg.ws.api.core.profileservice.ProfileService#memberChangePassword(java.lang.String  serviceID ,)java.lang.String  servicePWD ,)java.lang.String  memberID ,)java.lang.String  oldPassword ,)java.lang.String  newPassword )*
     */
    public tw.com.aptg.ws.api.core.profileservice.Response memberChangePassword(java.lang.String serviceID,java.lang.String servicePWD,java.lang.String memberID,java.lang.String oldPassword,java.lang.String newPassword) { 
        LOG.info("Executing operation memberChangePassword");
        System.out.println(serviceID);
        System.out.println(servicePWD);
        System.out.println(memberID);
        System.out.println(oldPassword);
        System.out.println(newPassword);
        try {
            tw.com.aptg.ws.api.core.profileservice.Response _return = new tw.com.aptg.ws.api.core.profileservice.Response();
            _return.setDescription("Description1608591881");
            tw.com.aptg.ws.api.core.profileservice.Profile _returnProfile = new tw.com.aptg.ws.api.core.profileservice.Profile();
            tw.com.aptg.ws.api.core.profileservice.Acceptance _returnProfileAcceptEpaper = tw.com.aptg.ws.api.core.profileservice.Acceptance.N;
            _returnProfile.setAcceptEpaper(_returnProfileAcceptEpaper);
            _returnProfile.setAddress("Address-762744967");
            _returnProfile.setBc("Bc279823343");
            _returnProfile.setBirthday("Birthday630192455");
            _returnProfile.setBscsCOID("BscsCOID-1740254552");
            _returnProfile.setBscsCSCODE("BscsCSCODE295563739");
            _returnProfile.setBscsCSID("BscsCSID-833434779");
            _returnProfile.setCompanyName("CompanyName-1593066576");
            _returnProfile.setContactPhone("ContactPhone1265994128");
            _returnProfile.setContractID("ContractID1246362064");
            tw.com.aptg.ws.api.core.profileservice.YesNoOption _returnProfileContractStatus = tw.com.aptg.ws.api.core.profileservice.YesNoOption.Y;
            _returnProfile.setContractStatus(_returnProfileContractStatus);
            _returnProfile.setContractStatusCode("ContractStatusCode-98115896");
            _returnProfile.setCustomerID("CustomerID-1491866055");
            _returnProfile.setDisableWeb("DisableWeb-1685250752");
            _returnProfile.setEducation("Education1156816679");
            _returnProfile.setEmail("Email-1495896683");
            _returnProfile.setEname("Ename-1291947994");
            tw.com.aptg.ws.api.core.profileservice.Gender _returnProfileGender = tw.com.aptg.ws.api.core.profileservice.Gender.F;
            _returnProfile.setGender(_returnProfileGender);
            tw.com.aptg.ws.api.core.profileservice.YesNoOption _returnProfileIsAdult = tw.com.aptg.ws.api.core.profileservice.YesNoOption.N;
            _returnProfile.setIsAdult(_returnProfileIsAdult);
            _returnProfile.setJobTitle("JobTitle-1785102242");
            _returnProfile.setMdn("Mdn2083550826");
            _returnProfile.setMin("Min1566153240");
            _returnProfile.setMobile1("Mobile1-1527109076");
            _returnProfile.setMobile2("Mobile2-1300142923");
            _returnProfile.setMobilePhoneType("MobilePhoneType1759510878");
            _returnProfile.setName("Name1768045475");
            _returnProfile.setNickname("Nickname-1285645205");
            _returnProfile.setOccupation("Occupation-2142912072");
            _returnProfile.setOtpStatus("OtpStatus-447335538");
            _returnProfile.setPersonalID("PersonalID1956029047");
            _returnProfile.setProductType("ProductType1787935686");
            _returnProfile.setPromotionCode("PromotionCode-1816118125");
            _returnProfile.setPushMail("PushMail789771763");
            _returnProfile.setSmscMail("SmscMail2123421031");
            _returnProfile.setTelphone1("Telphone1422007420");
            _returnProfile.setTelphone2("Telphone21272930632");
            _returnProfile.setTerminateType("TerminateType1896491879");
            _returnProfile.setUid("Uid119132885");
            _returnProfile.setUserType("UserType-1497407525");
            _return.setProfile(_returnProfile);
            _return.setResultCode("ResultCode1255723954");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see tw.com.aptg.ws.api.core.profileservice.ProfileService#subscriberChangePassword(java.lang.String  serviceID ,)java.lang.String  servicePWD ,)java.lang.String  mdn ,)java.lang.String  oldPassword ,)java.lang.String  newPassword )*
     */
    public tw.com.aptg.ws.api.core.profileservice.Response subscriberChangePassword(java.lang.String serviceID,java.lang.String servicePWD,java.lang.String mdn,java.lang.String oldPassword,java.lang.String newPassword) { 
        LOG.info("Executing operation subscriberChangePassword");
        System.out.println(serviceID);
        System.out.println(servicePWD);
        System.out.println(mdn);
        System.out.println(oldPassword);
        System.out.println(newPassword);
        try {
            tw.com.aptg.ws.api.core.profileservice.Response _return = new tw.com.aptg.ws.api.core.profileservice.Response();
            _return.setDescription("Description498870101");
            tw.com.aptg.ws.api.core.profileservice.Profile _returnProfile = new tw.com.aptg.ws.api.core.profileservice.Profile();
            tw.com.aptg.ws.api.core.profileservice.Acceptance _returnProfileAcceptEpaper = tw.com.aptg.ws.api.core.profileservice.Acceptance.N;
            _returnProfile.setAcceptEpaper(_returnProfileAcceptEpaper);
            _returnProfile.setAddress("Address-1875783655");
            _returnProfile.setBc("Bc1801391302");
            _returnProfile.setBirthday("Birthday298998703");
            _returnProfile.setBscsCOID("BscsCOID-623406450");
            _returnProfile.setBscsCSCODE("BscsCSCODE69033316");
            _returnProfile.setBscsCSID("BscsCSID505358364");
            _returnProfile.setCompanyName("CompanyName1459909157");
            _returnProfile.setContactPhone("ContactPhone2105066088");
            _returnProfile.setContractID("ContractID-916787657");
            tw.com.aptg.ws.api.core.profileservice.YesNoOption _returnProfileContractStatus = tw.com.aptg.ws.api.core.profileservice.YesNoOption.N;
            _returnProfile.setContractStatus(_returnProfileContractStatus);
            _returnProfile.setContractStatusCode("ContractStatusCode-1701231469");
            _returnProfile.setCustomerID("CustomerID1756630115");
            _returnProfile.setDisableWeb("DisableWeb-1625815826");
            _returnProfile.setEducation("Education-1419754530");
            _returnProfile.setEmail("Email-2011535174");
            _returnProfile.setEname("Ename-261667515");
            tw.com.aptg.ws.api.core.profileservice.Gender _returnProfileGender = tw.com.aptg.ws.api.core.profileservice.Gender.M;
            _returnProfile.setGender(_returnProfileGender);
            tw.com.aptg.ws.api.core.profileservice.YesNoOption _returnProfileIsAdult = tw.com.aptg.ws.api.core.profileservice.YesNoOption.N;
            _returnProfile.setIsAdult(_returnProfileIsAdult);
            _returnProfile.setJobTitle("JobTitle520635186");
            _returnProfile.setMdn("Mdn2118825719");
            _returnProfile.setMin("Min42323740");
            _returnProfile.setMobile1("Mobile11041119625");
            _returnProfile.setMobile2("Mobile2-456665697");
            _returnProfile.setMobilePhoneType("MobilePhoneType-1419467599");
            _returnProfile.setName("Name-157630363");
            _returnProfile.setNickname("Nickname632918903");
            _returnProfile.setOccupation("Occupation300071970");
            _returnProfile.setOtpStatus("OtpStatus1089367379");
            _returnProfile.setPersonalID("PersonalID448056098");
            _returnProfile.setProductType("ProductType993996979");
            _returnProfile.setPromotionCode("PromotionCode-834335214");
            _returnProfile.setPushMail("PushMail-1266749418");
            _returnProfile.setSmscMail("SmscMail-1975100798");
            _returnProfile.setTelphone1("Telphone1-1985595740");
            _returnProfile.setTelphone2("Telphone21923880428");
            _returnProfile.setTerminateType("TerminateType-1436280989");
            _returnProfile.setUid("Uid1514626380");
            _returnProfile.setUserType("UserType-992902540");
            _return.setProfile(_returnProfile);
            _return.setResultCode("ResultCode20190343");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see tw.com.aptg.ws.api.core.profileservice.ProfileService#subscriberResetPassword(java.lang.String  serviceID ,)java.lang.String  servicePWD ,)java.lang.String  mdn ,)java.lang.String  personID )*
     */
    public tw.com.aptg.ws.api.core.profileservice.Response subscriberResetPassword(java.lang.String serviceID,java.lang.String servicePWD,java.lang.String mdn,java.lang.String personID) { 
        LOG.info("Executing operation subscriberResetPassword");
        System.out.println(serviceID);
        System.out.println(servicePWD);
        System.out.println(mdn);
        System.out.println(personID);
        try {
            tw.com.aptg.ws.api.core.profileservice.Response _return = new tw.com.aptg.ws.api.core.profileservice.Response();
            _return.setDescription("Description-1286623742");
            tw.com.aptg.ws.api.core.profileservice.Profile _returnProfile = new tw.com.aptg.ws.api.core.profileservice.Profile();
            tw.com.aptg.ws.api.core.profileservice.Acceptance _returnProfileAcceptEpaper = tw.com.aptg.ws.api.core.profileservice.Acceptance.Y;
            _returnProfile.setAcceptEpaper(_returnProfileAcceptEpaper);
            _returnProfile.setAddress("Address322337999");
            _returnProfile.setBc("Bc2065859467");
            _returnProfile.setBirthday("Birthday1712972407");
            _returnProfile.setBscsCOID("BscsCOID-1652929163");
            _returnProfile.setBscsCSCODE("BscsCSCODE-850991638");
            _returnProfile.setBscsCSID("BscsCSID-101872860");
            _returnProfile.setCompanyName("CompanyName1436425384");
            _returnProfile.setContactPhone("ContactPhone-823996521");
            _returnProfile.setContractID("ContractID1658641862");
            tw.com.aptg.ws.api.core.profileservice.YesNoOption _returnProfileContractStatus = tw.com.aptg.ws.api.core.profileservice.YesNoOption.Y;
            _returnProfile.setContractStatus(_returnProfileContractStatus);
            _returnProfile.setContractStatusCode("ContractStatusCode1272777155");
            _returnProfile.setCustomerID("CustomerID-1850858096");
            _returnProfile.setDisableWeb("DisableWeb-1238848331");
            _returnProfile.setEducation("Education965310018");
            _returnProfile.setEmail("Email-522648994");
            _returnProfile.setEname("Ename721486355");
            tw.com.aptg.ws.api.core.profileservice.Gender _returnProfileGender = tw.com.aptg.ws.api.core.profileservice.Gender.M;
            _returnProfile.setGender(_returnProfileGender);
            tw.com.aptg.ws.api.core.profileservice.YesNoOption _returnProfileIsAdult = tw.com.aptg.ws.api.core.profileservice.YesNoOption.Y;
            _returnProfile.setIsAdult(_returnProfileIsAdult);
            _returnProfile.setJobTitle("JobTitle-1823461665");
            _returnProfile.setMdn("Mdn-2008162269");
            _returnProfile.setMin("Min990318459");
            _returnProfile.setMobile1("Mobile1961400562");
            _returnProfile.setMobile2("Mobile21036652061");
            _returnProfile.setMobilePhoneType("MobilePhoneType-1807831319");
            _returnProfile.setName("Name1664523690");
            _returnProfile.setNickname("Nickname-847931240");
            _returnProfile.setOccupation("Occupation1101283911");
            _returnProfile.setOtpStatus("OtpStatus-1519589689");
            _returnProfile.setPersonalID("PersonalID-614102427");
            _returnProfile.setProductType("ProductType627893621");
            _returnProfile.setPromotionCode("PromotionCode1445251076");
            _returnProfile.setPushMail("PushMail333274028");
            _returnProfile.setSmscMail("SmscMail59017226");
            _returnProfile.setTelphone1("Telphone1-867861507");
            _returnProfile.setTelphone2("Telphone21096154076");
            _returnProfile.setTerminateType("TerminateType1270243498");
            _returnProfile.setUid("Uid774261152");
            _returnProfile.setUserType("UserType-348286013");
            _return.setProfile(_returnProfile);
            _return.setResultCode("ResultCode768807381");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see tw.com.aptg.ws.api.core.profileservice.ProfileService#getTerminateProfile(java.lang.String  serviceID ,)java.lang.String  servicePWD ,)java.lang.String  userID ,)java.lang.String  contractID ,)java.lang.String  mdn ,)java.lang.String  min )*
     */
    public tw.com.aptg.ws.api.core.profileservice.TerminateResponse getTerminateProfile(java.lang.String serviceID,java.lang.String servicePWD,java.lang.String userID,java.lang.String contractID,java.lang.String mdn,java.lang.String min) { 
        LOG.info("Executing operation getTerminateProfile");
        System.out.println(serviceID);
        System.out.println(servicePWD);
        System.out.println(userID);
        System.out.println(contractID);
        System.out.println(mdn);
        System.out.println(min);
        try {
            tw.com.aptg.ws.api.core.profileservice.TerminateResponse _return = new tw.com.aptg.ws.api.core.profileservice.TerminateResponse();
            _return.setDescription("Description-1946414907");
            _return.setResultCode("ResultCode-74908389");
            tw.com.aptg.ws.api.core.profileservice.TerminateProfile _returnTerminateprofile = new tw.com.aptg.ws.api.core.profileservice.TerminateProfile();
            _returnTerminateprofile.setDuplicate(false);
            tw.com.aptg.ws.api.core.profileservice.Profile _returnTerminateprofileProfile = new tw.com.aptg.ws.api.core.profileservice.Profile();
            tw.com.aptg.ws.api.core.profileservice.Acceptance _returnTerminateprofileProfileAcceptEpaper = tw.com.aptg.ws.api.core.profileservice.Acceptance.Y;
            _returnTerminateprofileProfile.setAcceptEpaper(_returnTerminateprofileProfileAcceptEpaper);
            _returnTerminateprofileProfile.setAddress("Address-2138582772");
            _returnTerminateprofileProfile.setBc("Bc-1991858722");
            _returnTerminateprofileProfile.setBirthday("Birthday-1034469370");
            _returnTerminateprofileProfile.setBscsCOID("BscsCOID-1138673801");
            _returnTerminateprofileProfile.setBscsCSCODE("BscsCSCODE-64135186");
            _returnTerminateprofileProfile.setBscsCSID("BscsCSID-112059520");
            _returnTerminateprofileProfile.setCompanyName("CompanyName1179006000");
            _returnTerminateprofileProfile.setContactPhone("ContactPhone-1138693889");
            _returnTerminateprofileProfile.setContractID("ContractID-1001323067");
            tw.com.aptg.ws.api.core.profileservice.YesNoOption _returnTerminateprofileProfileContractStatus = tw.com.aptg.ws.api.core.profileservice.YesNoOption.Y;
            _returnTerminateprofileProfile.setContractStatus(_returnTerminateprofileProfileContractStatus);
            _returnTerminateprofileProfile.setContractStatusCode("ContractStatusCode456896284");
            _returnTerminateprofileProfile.setCustomerID("CustomerID724275058");
            _returnTerminateprofileProfile.setDisableWeb("DisableWeb-145245513");
            _returnTerminateprofileProfile.setEducation("Education-265500895");
            _returnTerminateprofileProfile.setEmail("Email-1267575974");
            _returnTerminateprofileProfile.setEname("Ename478121409");
            tw.com.aptg.ws.api.core.profileservice.Gender _returnTerminateprofileProfileGender = tw.com.aptg.ws.api.core.profileservice.Gender.F;
            _returnTerminateprofileProfile.setGender(_returnTerminateprofileProfileGender);
            tw.com.aptg.ws.api.core.profileservice.YesNoOption _returnTerminateprofileProfileIsAdult = tw.com.aptg.ws.api.core.profileservice.YesNoOption.N;
            _returnTerminateprofileProfile.setIsAdult(_returnTerminateprofileProfileIsAdult);
            _returnTerminateprofileProfile.setJobTitle("JobTitle-914839784");
            _returnTerminateprofileProfile.setMdn("Mdn-835736714");
            _returnTerminateprofileProfile.setMin("Min735713540");
            _returnTerminateprofileProfile.setMobile1("Mobile12077658536");
            _returnTerminateprofileProfile.setMobile2("Mobile2-967513456");
            _returnTerminateprofileProfile.setMobilePhoneType("MobilePhoneType-436102119");
            _returnTerminateprofileProfile.setName("Name-568709261");
            _returnTerminateprofileProfile.setNickname("Nickname1602122186");
            _returnTerminateprofileProfile.setOccupation("Occupation1382769088");
            _returnTerminateprofileProfile.setOtpStatus("OtpStatus-777840428");
            _returnTerminateprofileProfile.setPersonalID("PersonalID1143926668");
            _returnTerminateprofileProfile.setProductType("ProductType760716036");
            _returnTerminateprofileProfile.setPromotionCode("PromotionCode303236448");
            _returnTerminateprofileProfile.setPushMail("PushMail-2098958247");
            _returnTerminateprofileProfile.setSmscMail("SmscMail-548997256");
            _returnTerminateprofileProfile.setTelphone1("Telphone1-1718961973");
            _returnTerminateprofileProfile.setTelphone2("Telphone2-2062561519");
            _returnTerminateprofileProfile.setTerminateType("TerminateType1647423747");
            _returnTerminateprofileProfile.setUid("Uid864515676");
            _returnTerminateprofileProfile.setUserType("UserType-1468613142");
            _returnTerminateprofile.setProfile(_returnTerminateprofileProfile);
            _returnTerminateprofile.setRecordDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-03-22T12:05:10.804+08:00"));
            _returnTerminateprofile.setTerminateType("TerminateType1944655058");
            _return.setTerminateprofile(_returnTerminateprofile);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see tw.com.aptg.ws.api.core.profileservice.ProfileService#setReadAgreement(java.lang.String  serviceID ,)java.lang.String  servicePWD ,)java.lang.String  userID ,)java.lang.String  contractID ,)java.lang.String  mdn ,)java.lang.String  min )*
     */
    public tw.com.aptg.ws.api.core.profileservice.Response setReadAgreement(java.lang.String serviceID,java.lang.String servicePWD,java.lang.String userID,java.lang.String contractID,java.lang.String mdn,java.lang.String min) { 
        LOG.info("Executing operation setReadAgreement");
        System.out.println(serviceID);
        System.out.println(servicePWD);
        System.out.println(userID);
        System.out.println(contractID);
        System.out.println(mdn);
        System.out.println(min);
        try {
            tw.com.aptg.ws.api.core.profileservice.Response _return = new tw.com.aptg.ws.api.core.profileservice.Response();
            _return.setDescription("Description1500631355");
            tw.com.aptg.ws.api.core.profileservice.Profile _returnProfile = new tw.com.aptg.ws.api.core.profileservice.Profile();
            tw.com.aptg.ws.api.core.profileservice.Acceptance _returnProfileAcceptEpaper = tw.com.aptg.ws.api.core.profileservice.Acceptance.N;
            _returnProfile.setAcceptEpaper(_returnProfileAcceptEpaper);
            _returnProfile.setAddress("Address1363958145");
            _returnProfile.setBc("Bc-494557257");
            _returnProfile.setBirthday("Birthday-905610723");
            _returnProfile.setBscsCOID("BscsCOID924401491");
            _returnProfile.setBscsCSCODE("BscsCSCODE-1527153585");
            _returnProfile.setBscsCSID("BscsCSID249473499");
            _returnProfile.setCompanyName("CompanyName-2146084774");
            _returnProfile.setContactPhone("ContactPhone-1436280296");
            _returnProfile.setContractID("ContractID1307668019");
            tw.com.aptg.ws.api.core.profileservice.YesNoOption _returnProfileContractStatus = tw.com.aptg.ws.api.core.profileservice.YesNoOption.N;
            _returnProfile.setContractStatus(_returnProfileContractStatus);
            _returnProfile.setContractStatusCode("ContractStatusCode-839248033");
            _returnProfile.setCustomerID("CustomerID1914182819");
            _returnProfile.setDisableWeb("DisableWeb1528969199");
            _returnProfile.setEducation("Education2034696171");
            _returnProfile.setEmail("Email-628725066");
            _returnProfile.setEname("Ename-578404678");
            tw.com.aptg.ws.api.core.profileservice.Gender _returnProfileGender = tw.com.aptg.ws.api.core.profileservice.Gender.M;
            _returnProfile.setGender(_returnProfileGender);
            tw.com.aptg.ws.api.core.profileservice.YesNoOption _returnProfileIsAdult = tw.com.aptg.ws.api.core.profileservice.YesNoOption.Y;
            _returnProfile.setIsAdult(_returnProfileIsAdult);
            _returnProfile.setJobTitle("JobTitle1721616812");
            _returnProfile.setMdn("Mdn261510998");
            _returnProfile.setMin("Min-1625398583");
            _returnProfile.setMobile1("Mobile1-740796576");
            _returnProfile.setMobile2("Mobile21476968756");
            _returnProfile.setMobilePhoneType("MobilePhoneType317772474");
            _returnProfile.setName("Name773127494");
            _returnProfile.setNickname("Nickname-65342580");
            _returnProfile.setOccupation("Occupation-886964213");
            _returnProfile.setOtpStatus("OtpStatus1120220615");
            _returnProfile.setPersonalID("PersonalID-212417631");
            _returnProfile.setProductType("ProductType-647749616");
            _returnProfile.setPromotionCode("PromotionCode1225097500");
            _returnProfile.setPushMail("PushMail-1994063219");
            _returnProfile.setSmscMail("SmscMail1572885070");
            _returnProfile.setTelphone1("Telphone1-1096915476");
            _returnProfile.setTelphone2("Telphone2-1499629531");
            _returnProfile.setTerminateType("TerminateType1397740069");
            _returnProfile.setUid("Uid634636925");
            _returnProfile.setUserType("UserType-327552060");
            _return.setProfile(_returnProfile);
            _return.setResultCode("ResultCode-2004949863");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see tw.com.aptg.ws.api.core.profileservice.ProfileService#getUserProfile(java.lang.String  serviceID ,)java.lang.String  servicePWD ,)java.lang.String  userID ,)java.lang.String  contractID ,)java.lang.String  mdn ,)java.lang.String  min ,)java.lang.String  email )*
     */
    public tw.com.aptg.ws.api.core.profileservice.Response getUserProfile(java.lang.String serviceID,java.lang.String servicePWD,java.lang.String userID,java.lang.String contractID,java.lang.String mdn,java.lang.String min,java.lang.String email) { 
        LOG.info("Executing operation getUserProfile");
        System.out.println(serviceID);
        System.out.println(servicePWD);
        System.out.println(userID);
        System.out.println(contractID);
        System.out.println(mdn);
        System.out.println(min);
        System.out.println(email);
        try {
            tw.com.aptg.ws.api.core.profileservice.Response _return = new tw.com.aptg.ws.api.core.profileservice.Response();
            _return.setDescription("Description80132029");
            tw.com.aptg.ws.api.core.profileservice.Profile _returnProfile = new tw.com.aptg.ws.api.core.profileservice.Profile();
            tw.com.aptg.ws.api.core.profileservice.Acceptance _returnProfileAcceptEpaper = tw.com.aptg.ws.api.core.profileservice.Acceptance.Y;
            _returnProfile.setAcceptEpaper(_returnProfileAcceptEpaper);
            _returnProfile.setAddress("Address-1111553769");
            _returnProfile.setBc("Bc977399496");
            _returnProfile.setBirthday("Birthday550125811");
            _returnProfile.setBscsCOID("BscsCOID-1591216855");
            _returnProfile.setBscsCSCODE("BscsCSCODE-947953481");
            _returnProfile.setBscsCSID("BscsCSID-2078248131");
            _returnProfile.setCompanyName("CompanyName-397957273");
            _returnProfile.setContactPhone("ContactPhone592457367");
            _returnProfile.setContractID("ContractID-1966125451");
            tw.com.aptg.ws.api.core.profileservice.YesNoOption _returnProfileContractStatus = tw.com.aptg.ws.api.core.profileservice.YesNoOption.Y;
            _returnProfile.setContractStatus(_returnProfileContractStatus);
            _returnProfile.setContractStatusCode("ContractStatusCode762251147");
            _returnProfile.setCustomerID("CustomerID1972519859");
            _returnProfile.setDisableWeb("DisableWeb-1157200869");
            _returnProfile.setEducation("Education65915514");
            _returnProfile.setEmail("Email393588924");
            _returnProfile.setEname("Ename1947537174");
            tw.com.aptg.ws.api.core.profileservice.Gender _returnProfileGender = tw.com.aptg.ws.api.core.profileservice.Gender.M;
            _returnProfile.setGender(_returnProfileGender);
            tw.com.aptg.ws.api.core.profileservice.YesNoOption _returnProfileIsAdult = tw.com.aptg.ws.api.core.profileservice.YesNoOption.Y;
            _returnProfile.setIsAdult(_returnProfileIsAdult);
            _returnProfile.setJobTitle("JobTitle1302651542");
            _returnProfile.setMdn("Mdn1128971503");
            _returnProfile.setMin("Min1433236628");
            _returnProfile.setMobile1("Mobile1-254675415");
            _returnProfile.setMobile2("Mobile2-502887549");
            _returnProfile.setMobilePhoneType("MobilePhoneType1999038466");
            _returnProfile.setName("Name1809730275");
            _returnProfile.setNickname("Nickname-1698769006");
            _returnProfile.setOccupation("Occupation-1895375723");
            _returnProfile.setOtpStatus("OtpStatus-1691680013");
            _returnProfile.setPersonalID("PersonalID-435127109");
            _returnProfile.setProductType("ProductType1066490119");
            _returnProfile.setPromotionCode("PromotionCode-1183136106");
            _returnProfile.setPushMail("PushMail-1980132923");
            _returnProfile.setSmscMail("SmscMail1385836997");
            _returnProfile.setTelphone1("Telphone1-1428473672");
            _returnProfile.setTelphone2("Telphone2-957828004");
            _returnProfile.setTerminateType("TerminateType522516380");
            _returnProfile.setUid("Uid-1919343204");
            _returnProfile.setUserType("UserType-1814026957");
            _return.setProfile(_returnProfile);
            _return.setResultCode("ResultCode-403564960");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
