
package tw.com.aptg.ws.api.core.profileservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2018-03-22T12:05:10.613+08:00
 * Generated source version: 2.7.18
 * 
 */
public final class ProfileService_ProfileServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.aptg.com.tw/ws/api/core/ProfileService", "ProfileService");

    private ProfileService_ProfileServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ProfileService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ProfileService_Service ss = new ProfileService_Service(wsdlURL, SERVICE_NAME);
        ProfileService port = ss.getProfileServicePort();  
        
        {
        System.out.println("Invoking memberChangeAccount...");
        java.lang.String _memberChangeAccount_serviceID = "_memberChangeAccount_serviceID-2132922626";
        java.lang.String _memberChangeAccount_servicePWD = "_memberChangeAccount_servicePWD67900891";
        java.lang.String _memberChangeAccount_oldAccountID = "_memberChangeAccount_oldAccountID-1352241657";
        java.lang.String _memberChangeAccount_personID = "_memberChangeAccount_personID1601736721";
        java.lang.String _memberChangeAccount_newAccountID = "_memberChangeAccount_newAccountID970941090";
        tw.com.aptg.ws.api.core.profileservice.Response _memberChangeAccount__return = port.memberChangeAccount(_memberChangeAccount_serviceID, _memberChangeAccount_servicePWD, _memberChangeAccount_oldAccountID, _memberChangeAccount_personID, _memberChangeAccount_newAccountID);
        System.out.println("memberChangeAccount.result=" + _memberChangeAccount__return);


        }
        {
        System.out.println("Invoking memberResetPassword...");
        java.lang.String _memberResetPassword_serviceID = "_memberResetPassword_serviceID2066224280";
        java.lang.String _memberResetPassword_servicePWD = "_memberResetPassword_servicePWD769726711";
        java.lang.String _memberResetPassword_memberID = "_memberResetPassword_memberID222289695";
        java.lang.String _memberResetPassword_personID = "_memberResetPassword_personID-1689579985";
        tw.com.aptg.ws.api.core.profileservice.Response _memberResetPassword__return = port.memberResetPassword(_memberResetPassword_serviceID, _memberResetPassword_servicePWD, _memberResetPassword_memberID, _memberResetPassword_personID);
        System.out.println("memberResetPassword.result=" + _memberResetPassword__return);


        }
        {
        System.out.println("Invoking setContractEMail...");
        java.lang.String _setContractEMail_serviceID = "_setContractEMail_serviceID650669862";
        java.lang.String _setContractEMail_servicePWD = "_setContractEMail_servicePWD-2001363504";
        java.lang.String _setContractEMail_userID = "_setContractEMail_userID1397405336";
        java.lang.String _setContractEMail_contractID = "_setContractEMail_contractID2077853029";
        java.lang.String _setContractEMail_mdn = "_setContractEMail_mdn-1450812543";
        java.lang.String _setContractEMail_min = "_setContractEMail_min-31103465";
        java.lang.String _setContractEMail_email = "_setContractEMail_email-1508925603";
        tw.com.aptg.ws.api.core.profileservice.Response _setContractEMail__return = port.setContractEMail(_setContractEMail_serviceID, _setContractEMail_servicePWD, _setContractEMail_userID, _setContractEMail_contractID, _setContractEMail_mdn, _setContractEMail_min, _setContractEMail_email);
        System.out.println("setContractEMail.result=" + _setContractEMail__return);


        }
        {
        System.out.println("Invoking memberChangePassword...");
        java.lang.String _memberChangePassword_serviceID = "_memberChangePassword_serviceID175888411";
        java.lang.String _memberChangePassword_servicePWD = "_memberChangePassword_servicePWD1632130503";
        java.lang.String _memberChangePassword_memberID = "_memberChangePassword_memberID-139998684";
        java.lang.String _memberChangePassword_oldPassword = "_memberChangePassword_oldPassword-1775493726";
        java.lang.String _memberChangePassword_newPassword = "_memberChangePassword_newPassword-588376257";
        tw.com.aptg.ws.api.core.profileservice.Response _memberChangePassword__return = port.memberChangePassword(_memberChangePassword_serviceID, _memberChangePassword_servicePWD, _memberChangePassword_memberID, _memberChangePassword_oldPassword, _memberChangePassword_newPassword);
        System.out.println("memberChangePassword.result=" + _memberChangePassword__return);


        }
        {
        System.out.println("Invoking subscriberChangePassword...");
        java.lang.String _subscriberChangePassword_serviceID = "_subscriberChangePassword_serviceID490412775";
        java.lang.String _subscriberChangePassword_servicePWD = "_subscriberChangePassword_servicePWD1813678014";
        java.lang.String _subscriberChangePassword_mdn = "_subscriberChangePassword_mdn-1060205376";
        java.lang.String _subscriberChangePassword_oldPassword = "_subscriberChangePassword_oldPassword-407214565";
        java.lang.String _subscriberChangePassword_newPassword = "_subscriberChangePassword_newPassword1532172953";
        tw.com.aptg.ws.api.core.profileservice.Response _subscriberChangePassword__return = port.subscriberChangePassword(_subscriberChangePassword_serviceID, _subscriberChangePassword_servicePWD, _subscriberChangePassword_mdn, _subscriberChangePassword_oldPassword, _subscriberChangePassword_newPassword);
        System.out.println("subscriberChangePassword.result=" + _subscriberChangePassword__return);


        }
        {
        System.out.println("Invoking subscriberResetPassword...");
        java.lang.String _subscriberResetPassword_serviceID = "_subscriberResetPassword_serviceID19955457";
        java.lang.String _subscriberResetPassword_servicePWD = "_subscriberResetPassword_servicePWD1673618505";
        java.lang.String _subscriberResetPassword_mdn = "_subscriberResetPassword_mdn-1383769127";
        java.lang.String _subscriberResetPassword_personID = "_subscriberResetPassword_personID1763611789";
        tw.com.aptg.ws.api.core.profileservice.Response _subscriberResetPassword__return = port.subscriberResetPassword(_subscriberResetPassword_serviceID, _subscriberResetPassword_servicePWD, _subscriberResetPassword_mdn, _subscriberResetPassword_personID);
        System.out.println("subscriberResetPassword.result=" + _subscriberResetPassword__return);


        }
        {
        System.out.println("Invoking getTerminateProfile...");
        java.lang.String _getTerminateProfile_serviceID = "_getTerminateProfile_serviceID-820717176";
        java.lang.String _getTerminateProfile_servicePWD = "_getTerminateProfile_servicePWD-1942144419";
        java.lang.String _getTerminateProfile_userID = "_getTerminateProfile_userID-637503159";
        java.lang.String _getTerminateProfile_contractID = "_getTerminateProfile_contractID-1149250329";
        java.lang.String _getTerminateProfile_mdn = "_getTerminateProfile_mdn1610022855";
        java.lang.String _getTerminateProfile_min = "_getTerminateProfile_min-1809311941";
        tw.com.aptg.ws.api.core.profileservice.TerminateResponse _getTerminateProfile__return = port.getTerminateProfile(_getTerminateProfile_serviceID, _getTerminateProfile_servicePWD, _getTerminateProfile_userID, _getTerminateProfile_contractID, _getTerminateProfile_mdn, _getTerminateProfile_min);
        System.out.println("getTerminateProfile.result=" + _getTerminateProfile__return);


        }
        {
        System.out.println("Invoking setReadAgreement...");
        java.lang.String _setReadAgreement_serviceID = "_setReadAgreement_serviceID-546851104";
        java.lang.String _setReadAgreement_servicePWD = "_setReadAgreement_servicePWD778716137";
        java.lang.String _setReadAgreement_userID = "_setReadAgreement_userID1100349624";
        java.lang.String _setReadAgreement_contractID = "_setReadAgreement_contractID482209306";
        java.lang.String _setReadAgreement_mdn = "_setReadAgreement_mdn1211854595";
        java.lang.String _setReadAgreement_min = "_setReadAgreement_min-936100623";
        tw.com.aptg.ws.api.core.profileservice.Response _setReadAgreement__return = port.setReadAgreement(_setReadAgreement_serviceID, _setReadAgreement_servicePWD, _setReadAgreement_userID, _setReadAgreement_contractID, _setReadAgreement_mdn, _setReadAgreement_min);
        System.out.println("setReadAgreement.result=" + _setReadAgreement__return);


        }
        {
        System.out.println("Invoking getUserProfile...");
        java.lang.String _getUserProfile_serviceID = "_getUserProfile_serviceID1999130553";
        java.lang.String _getUserProfile_servicePWD = "_getUserProfile_servicePWD-1996009671";
        java.lang.String _getUserProfile_userID = "_getUserProfile_userID37234821";
        java.lang.String _getUserProfile_contractID = "_getUserProfile_contractID1857740966";
        java.lang.String _getUserProfile_mdn = "_getUserProfile_mdn-1469645644";
        java.lang.String _getUserProfile_min = "_getUserProfile_min323004213";
        java.lang.String _getUserProfile_email = "_getUserProfile_email2007106926";
        tw.com.aptg.ws.api.core.profileservice.Response _getUserProfile__return = port.getUserProfile(_getUserProfile_serviceID, _getUserProfile_servicePWD, _getUserProfile_userID, _getUserProfile_contractID, _getUserProfile_mdn, _getUserProfile_min, _getUserProfile_email);
        System.out.println("getUserProfile.result=" + _getUserProfile__return);


        }

        System.exit(0);
    }

}
