package com.truetel.war.aptpns.iweb.ws.pbk;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2018-03-29T10:49:30.737+08:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://truetel.com/war/aptpns/iweb/ws/pbk", name = "PhonebookApi")
@XmlSeeAlso({ObjectFactory.class, com.truetel.war.aptpns.iweb.ws.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface PhonebookApi {

    @WebMethod(action = "urn:updateContact")
    @WebResult(name = "updateContactsResp", targetNamespace = "http://truetel.com/war/aptpns/iweb/ws/pbk", partName = "parameters")
    public UpdateContactsResp updateContacts(
        @WebParam(partName = "parameters", name = "updateContactsReq", targetNamespace = "http://truetel.com/war/aptpns/iweb/ws/pbk")
        UpdateContactsReq parameters
    ) throws ErrorException;

    @WebMethod(action = "urn:listContacts")
    @WebResult(name = "listContactsResp", targetNamespace = "http://truetel.com/war/aptpns/iweb/ws/pbk", partName = "parameters")
    public ListContactsResp listContacts(
        @WebParam(partName = "parameters", name = "listContactsReq", targetNamespace = "http://truetel.com/war/aptpns/iweb/ws/pbk")
        ListContactsReq parameters
    ) throws ErrorException;

    @WebMethod(action = "urn:createContacts")
    @WebResult(name = "createContactsResp", targetNamespace = "http://truetel.com/war/aptpns/iweb/ws/pbk", partName = "parameters")
    public CreateContactsResp createContacts(
        @WebParam(partName = "parameters", name = "createContactsReq", targetNamespace = "http://truetel.com/war/aptpns/iweb/ws/pbk")
        CreateContactsReq parameters
    ) throws ErrorException;

    @WebMethod
    @WebResult(name = "createGroupResp", targetNamespace = "http://truetel.com/war/aptpns/iweb/ws/pbk", partName = "parameters")
    public CreateGroupResp createGroup(
        @WebParam(partName = "parameters", name = "createGroupReq", targetNamespace = "http://truetel.com/war/aptpns/iweb/ws/pbk")
        CreateGroupReq parameters
    ) throws ErrorException;

    @WebMethod(action = "urn:countContacts")
    @WebResult(name = "countContactsResp", targetNamespace = "http://truetel.com/war/aptpns/iweb/ws/pbk", partName = "parameters")
    public CountContactsResp countContacts(
        @WebParam(partName = "parameters", name = "countContactsReq", targetNamespace = "http://truetel.com/war/aptpns/iweb/ws/pbk")
        CountContactsReq parameters
    ) throws ErrorException;

    @WebMethod(action = "urn:deleteContacts")
    @WebResult(name = "deleteContactsResp", targetNamespace = "http://truetel.com/war/aptpns/iweb/ws/pbk", partName = "parameters")
    public DeleteContactsResp deleteContacts(
        @WebParam(partName = "parameters", name = "deleteContactsReq", targetNamespace = "http://truetel.com/war/aptpns/iweb/ws/pbk")
        DeleteContactsReq parameters
    ) throws ErrorException;

    @WebMethod(action = "urn:addContactToGroup")
    @WebResult(name = "addContactToGroupResp", targetNamespace = "http://truetel.com/war/aptpns/iweb/ws/pbk", partName = "parameters")
    public AddContactToGroupResp addContactToGroup(
        @WebParam(partName = "parameters", name = "addContactToGroupReq", targetNamespace = "http://truetel.com/war/aptpns/iweb/ws/pbk")
        AddContactToGroupReq parameters
    ) throws ErrorException;

    @WebMethod(action = "urn:deleteGroup")
    @WebResult(name = "deleteGroupResp", targetNamespace = "http://truetel.com/war/aptpns/iweb/ws/pbk", partName = "parameters")
    public DeleteGroupResp deleteGroup(
        @WebParam(partName = "parameters", name = "deleteGroupReq", targetNamespace = "http://truetel.com/war/aptpns/iweb/ws/pbk")
        DeleteGroupReq parameters
    ) throws ErrorException;

    @WebMethod(action = "urn:removeContactFromGroup")
    @WebResult(name = "removeContactFromGroupResp", targetNamespace = "http://truetel.com/war/aptpns/iweb/ws/pbk", partName = "parameters")
    public RemoveContactFromGroupResp removeContactFromGroup(
        @WebParam(partName = "parameters", name = "removeContactFromGroupReq", targetNamespace = "http://truetel.com/war/aptpns/iweb/ws/pbk")
        RemoveContactFromGroupReq parameters
    ) throws ErrorException;

    @WebMethod(action = "urn:terminateSubrs")
    @WebResult(name = "terminateSubrsResp", targetNamespace = "http://truetel.com/war/aptpns/iweb/ws/pbk", partName = "parameters")
    public TerminateSubrsResp terminateSubrs(
        @WebParam(partName = "parameters", name = "terminateSubrsReq", targetNamespace = "http://truetel.com/war/aptpns/iweb/ws/pbk")
        TerminateSubrsReq parameters
    ) throws ErrorException;

    @WebMethod(action = "urn:listGroups")
    @WebResult(name = "listGroupsResp", targetNamespace = "http://truetel.com/war/aptpns/iweb/ws/pbk", partName = "parameters")
    public ListGroupsResp listGroups(
        @WebParam(partName = "parameters", name = "listGroupsReq", targetNamespace = "http://truetel.com/war/aptpns/iweb/ws/pbk")
        ListGroupsReq parameters
    ) throws ErrorException;
}
