/**
 * ================== Copyright Notice ===================
 * This file contains proprietary information of APTG.
 * Copying or reproduction without prior written
 * approval is prohibited.
 * Copyright (c) 2018
 *
 *
 * ------------------  History ---------------------------
 * Version   Date        Developer           Description
 * 01        20180329    Gary Chang          新增從config取得WSDL URL
 */


package com.truetel.war.aptpns.iweb.ws.pbk;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.ResourceBundle;

import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2018-03-29T10:49:30.751+08:00
 * Generated source version: 2.7.18
 * 
 */
@WebServiceClient(name = "PhonebookApiImplService", 
                  wsdlLocation = "http://10.31.79.5:6500/aptpnsiweb/PhonebookApi?wsdl",
                  targetNamespace = "http://truetel.com/war/aptpns/iweb/ws/pbk") 
public class PhonebookApiImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://truetel.com/war/aptpns/iweb/ws/pbk", "PhonebookApiImplService");
    public final static QName PhonebookApiPort = new QName("http://truetel.com/war/aptpns/iweb/ws/pbk", "PhonebookApiPort");
    static {
    	//#01
    	String wsdlLocation = "";
        URL url = null;
        try {
        	//#01
        	ResourceBundle config = ResourceBundle.getBundle("config");
        	wsdlLocation = config.getString("aptpns.service.wsdl.location");
            url = new URL(wsdlLocation);
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PhonebookApiImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://10.31.79.5:6500/aptpnsiweb/PhonebookApi?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PhonebookApiImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PhonebookApiImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PhonebookApiImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PhonebookApiImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PhonebookApiImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PhonebookApiImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns PhonebookApi
     */
    @WebEndpoint(name = "PhonebookApiPort")
    public PhonebookApi getPhonebookApiPort() {
        return super.getPort(PhonebookApiPort, PhonebookApi.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PhonebookApi
     */
    @WebEndpoint(name = "PhonebookApiPort")
    public PhonebookApi getPhonebookApiPort(WebServiceFeature... features) {
        return super.getPort(PhonebookApiPort, PhonebookApi.class, features);
    }

}
