/**
 * ================== Copyright Notice ===================
 * This file contains proprietary information of APTG.
 * Copying or reproduction without prior written
 * approval is prohibited.
 * Copyright (c) 2018
 *
 *
 * ------------------  History ---------------------------
 * Version   Date        Developer           Description
 * 01        20180323    Gary Chang          initial
 */


package tw.com.aptg.service;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.net.URL;

import javax.xml.namespace.QName;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import tw.com.aptg.ws.api.core.profileservice.Profile;
import tw.com.aptg.ws.api.core.profileservice.ProfileService;
import tw.com.aptg.ws.api.core.profileservice.ProfileService_Service;
import tw.com.aptg.ws.api.core.profileservice.Response;

/**
 * This class was generated by Apache CXF 2.7.18 2018-03-22T12:05:10.613+08:00
 * Generated source version: 2.7.18
 * 
 */
public final class ProfileServiceClient {
	private static final Logger logger = LogManager.getFormatterLogger(ProfileServiceClient.class.getName());    
	
	private static final QName SERVICE_NAME = new QName("http://www.aptg.com.tw/ws/api/core/ProfileService", "ProfileService");
	private String userID = "";
	private static final String serviceID = "apt_msg";
	private static final String servicePWD = "msg1234";
	
	public ProfileServiceClient(String userID) {
	   this.userID = userID;  
	}

	public Profile getUserProfile() {
		URL wsdlURL = ProfileService_Service.WSDL_LOCATION;
		ProfileService_Service ws = new ProfileService_Service(wsdlURL, SERVICE_NAME);
		ProfileService port = ws.getProfileServicePort();
		logger.info("UUID=" + this.userID);
		logger.info("Invoking getUserProfile...");

		String _getUserProfile_serviceID = serviceID;
		String _getUserProfile_servicePWD = servicePWD;
		String _getUserProfile_userID = this.userID;
		String _getUserProfile_contractID = null ;
		String _getUserProfile_mdn = null;
		String _getUserProfile_min = null;
		String _getUserProfile_email = null;
		Response _getUserProfile__return = port.getUserProfile(
				_getUserProfile_serviceID, _getUserProfile_servicePWD, _getUserProfile_userID,
				_getUserProfile_contractID, _getUserProfile_mdn, _getUserProfile_min, _getUserProfile_email);
			
		logger.info("ResultCode=" + _getUserProfile__return.getResultCode());
		logger.info("Description=" + _getUserProfile__return.getDescription());	
		/*
		 * ResultCode=00010004
		 * Description=no such profile
		 */		
		Profile profile = _getUserProfile__return.getProfile();
		return profile;
	}
	
	//For Test Sample
	public static void main(String args[]) throws java.lang.Exception {

		String uuid = "c86144d44-1dbb-11e0-8520-001517eb22c4"; // 0982688759
		//String uuid = ""; // 0982174118
		
		ProfileServiceClient wsClient = new ProfileServiceClient(uuid);
		Profile profile = wsClient.getUserProfile();
		System.out.println(profile.getAcceptEpaper());
		System.out.println(profile.getAddress());
		System.out.println(profile.getBc());
		System.out.println(profile.getBirthday());
		System.out.println(profile.getBscsCOID());
		System.out.println(profile.getBscsCSCODE());
		System.out.println(profile.getBscsCSID());
		System.out.println(profile.getCompanyName());
		System.out.println(profile.getContactPhone());
		System.out.println(profile.getContractID());
		System.out.println(profile.getContractStatus());
		System.out.println(profile.getContractStatusCode());
		System.out.println(profile.getCustomerID());
		System.out.println(profile.getDisableWeb());
		System.out.println(profile.getEducation());
		System.out.println(profile.getEmail());
		System.out.println(profile.getEname());		
		System.out.println(profile.getGender());
		System.out.println(profile.getIsAdult());
		System.out.println(profile.getJobTitle());		
		System.out.println(profile.getMdn());
		System.out.println(profile.getMin());
		System.out.println(profile.getMobile1());
		System.out.println(profile.getMobile2());
		System.out.println(profile.getMobilePhoneType());
		System.out.println(profile.getName());
		System.out.println(profile.getNickname());
		System.out.println(profile.getOccupation());
		System.out.println(profile.getOtpStatus());
		System.out.println(profile.getPersonalID());
		System.out.println(profile.getPromotionCode());
		System.out.println(profile.getPushMail());
		System.out.println(profile.getSmscMail());
		System.out.println(profile.getTelphone1());
		System.out.println(profile.getTelphone2());
		System.out.println(profile.getTerminateType());
		System.out.println(profile.getUid());
		System.out.println(profile.getUserType());
	}

}
